
# Simulate the "injector" logic
import os

TEMPLATE_PATH = "/Users/nikhilgundala/Desktop/NTB/DSA/practice-dsa-problems/templates/python_template.py"
STUB_PATH = "/Users/nikhilgundala/Desktop/NTB/DSA/practice-dsa-problems/Arrays/stubs/ARR-001/python/solution.py"

# User code (implementation of stub)
USER_CODE = """
def prefix_averages(arr: list[int]) -> list[int]:
    n = len(arr)
    result = []
    running_sum = 0
    for i in range(n):
        running_sum += arr[i]
        result.append(running_sum // (i + 1))
    return result
"""

# Adapter code (generated by backend usually, but hardcoded for test)
ADAPTER_CODE = """
def run_user_code(args):
    return prefix_averages(args[0])
"""

with open(TEMPLATE_PATH, 'r') as f:
    template = f.read()

# Replace placeholders
# Note: In real system, we'd replace markers. In my template I used:
# # [USER CODE INJECTED HERE]
# # [ADAPTER INJECTED HERE]

final_code = template.replace("# [USER CODE INJECTED HERE]", USER_CODE)
final_code = final_code.replace("# [ADAPTER INJECTED HERE]", ADAPTER_CODE)

with open("temp_runner.py", "w") as f:
    f.write(final_code)

print("Runner created at temp_runner.py")
